# Generated by Django 2.2 on 2020-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20200219_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default=0.0004987531172069825, max_length=255),
            preserve_default=False,
        ),
    ]
